name: SonarCloud Analysis

on:
  push:
    branches:
      - '**' # Trigger on all branches
  pull_request:
    branches:
      - '**' # Trigger on pull requests for all branches

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (SonarCloud requires Java)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11' # Use a version compatible with your SonarCloud configuration

      # Cache SonarCloud scanner binaries
      - name: Cache SonarCloud scanner
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Run SonarCloud analysis
      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Add this token as a repository secret
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Spiderjockey02_filehost-server \
            -Dsonar.organization=spiderjockey02 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.branch.name=${{ github.ref_name }} # Detects branch dynamically
